DROP TABLE IF EXISTS sales;
CREATE TABLE sales (
    id INTEGER PRIMARY KEY,
    event_name TEXT NOT NULL,
    event_url TEXT NOT NULL,
    ticket_sales_date DATETIME NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

